name: Build, test and deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Changing gradlew permission
      run: chmod +x ./gradlew

    - name: Build
      run: ./gradlew build -x test

    - name: Test
      run: ./gradlew test
